//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoLOJA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItensPedido
    {
        public long ID { get; set; }
        public long Produto { get; set; }
        public long Quantidade { get; set; }
        public decimal Valor { get; set; }
        public long Códigopedido { get; set; }
    
        public virtual Produto Produto1 { get; set; }
        public virtual Pedido Pedido { get; set; }
    }
}
